blog/urls.py
from django.urls import path
from . import views



app_name = 'blogs'

urlpatterns = [
    path('', views.home, name="home"),
    path('posts/category/<int:category_id>/', views.category, name="category"),
    path('posts/<int:id>/', views.blog, name="blog"),
]

webdocs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify

class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name

class Sector(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name

class Blog(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField(max_length=150, unique=True)
    tags = models.CharField(max_length=65)
    is_published = models.BooleanField(default=False)
    content = models.TextField()
    content_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    cover = models.ImageField(upload_to='blog/covers/%Y/%m/%d', blank=True, default='')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, default=None)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    sector = models.ForeignKey(Sector, on_delete=models.SET_NULL, null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        if not self.author and 'user' in kwargs:
            self.author = kwargs.pop('user')
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import get_list_or_404, get_object_or_404, render
from .models import Blog


def home(request):
    blogs = Blog.objects.filter(
        is_published=True
    ).order_by('-id')
    
    return render(request, 'blog/pages/home.html', context={
        'blogs': blogs,
        'title': 'WebDocs'
    })

def category(request, category_id):
    # Busca os blogs da categoria especificada, publicados, ordenados do mais recente para o mais antigo
    blogs = get_list_or_404(Blog.objects.filter(
        category__id=category_id,
        is_published=True
    ).order_by('-id'))
    
    return render(request, 'blog/pages/category.html', context={
        'blogs': blogs,
        'title': f'Categoria-{blogs[0].category.name}'
    })

def blog(request, id):
    blog_post = get_object_or_404(Blog, id=id, is_published=True)
    
    return render(request, 'blog/pages/post_view.html', context={
        'blog': blog_post,
        'is_detail_page': True,
    })

blog/templates/blog/pages/category.html
{% extends 'global/base.html' %}

{% block title %}{{ title }}{% endblock title %}

    {% block content %}

        <div class="main-content main-content-list container">
            {% for blog in blogs %}
            {% include 'blog\partials\post_blog.html' %}
            {% endfor %}

        </div>
        
    {% endblock content %}

blog/templates/blog/pages/home.html
{% extends 'global/base.html' %}

{% block title %}HOME |{% endblock title %}

    {% block content %}

        <div class="main-content main-content-list container">
            {% for blog in blogs %}
            {% include 'blog\partials\post_blog.html' %}
            {% endfor %}

        </div>
        
    {% endblock content %}

blog/templates/blog/pages/post_view.html
{% extends 'global/base.html' %}
{% block title %} {{blog.title}} {% endblock title %}
    {% block content %}
        <div class="main-content main-content-detail container">
            {% include 'blog\partials\post_blog.html' %}
        </div>
    {% endblock content %}

blog/templates/blog/partials/footer.html
<footer class="main-footer">

    <div class="developer">
        <a href="" target="_blank" rel="noreferrer noopener">By Michael Tavares</a>
    </div>

    <div class="powered">
        <a href="" target="_blank" rel="noreferrer noopener">{{ user.username }}</a>
      </div>

    <div class="powered">
      <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
    </div>

 
  </footer>

blog/templates/blog/partials/head.html
{% load static %}

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/fontawesome.min.css"
        integrity="sha512-B46MVOJpI6RBsdcU307elYeStF2JKT87SsHZfRSkjVi4/iZ3912zXi45X5/CBr/GbCyLx6M1GQtTKYRd52Jxgw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/brands.min.css"
        integrity="sha512-EJp8vMVhYl7tBFE2rgNGb//drnr1+6XKMvTyamMS34YwOEFohhWkGq13tPWnK0FbjSS6D8YoA3n3bZmb3KiUYA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/solid.min.css"
        integrity="sha512-/r+0SvLvMMSIf41xiuy19aNkXxI+3zb/BN8K9lnDDWI09VM0dwgTMzK7Qi5vv5macJ3VH4XZXr60ip7v13QnmQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />


<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">
    
<link rel="stylesheet" href="{% static 'blog\css\styles.css' %}">
<link rel="stylesheet" href="{% static 'global\css\global-styles.css' %}">
<link rel="icon" href="{% static 'blog/img/favicon.ico' %}" type="image/x-icon">


blog/templates/blog/partials/header.html
{% load static %}
<header class="main-header-container">
    <div class="main-container-logo">

        <img class="logo_image_claro" src="{% static 'blog/img/claro.png' %}" alt="Claro Logo">
        <a class="main-logo" href="{% url 'blogs:home' %}">
            <i class="fa-brands fa-docker main-logo-icon"></i>
            <span class="main-logo-text">Banco de Conhecimento</span>
        </a>

    </div>
</header>

blog/templates/blog/partials/post_blog.html
{% load static %}

<div class="banco  banco-list-item">
    <div class="banco-cover">
        <a href="{% url 'blogs:blog' blog.id %}">

        {% if blog.cover %}

            <img src="{{ blog.cover.url }}" alt="My image">
        
        {% else %}
        
            <img src="{% static 'blog/img/claro.png' %}" alt="My image">
        
        {% endif %}

        </a>
    </div>
    <div class="blog-title-container">
        <h2 class="blog-title">
            <a href="{% url 'blogs:blog' blog.id %}"> 
                {{ blog.title }} 
            </a>
        </h2>
    </div>
    <div class="blog-author">
        {% if blog.author is not None %}
            <span class="blog-author-item">
                <i class="fas fa-user"></i>
                {% if blog.author.first_name %}
                    {{ blog.author.first_name }} {{ blog.author.last_name }}
                {% else %}
                    {{ blog.author.username }}
                {% endif %}
            </span>
        {% endif %}

        <span class="blog-author-item">
            <i class="fas fas fa-calendar-alt"></i>
            {{ blog.created_at|date:"d/m/Y" }}  as {{ blog.created_at|date:"H:i" }}
        </span>
        
        {% if blog.category is not None %}
            <span class="blog-author-item">
                <a href="{% url 'blogs:category' blog.category.id %}">
                    <i class="fas fa-layer-group"></i>
                    <span>{{ blog.category.name }}</span>
                </a>
            </span>
        {% endif %}
            
    </div>

    <div class="blog-content">
        <p>{{ blog.description }}</p>
    </div>

    {% if is_detail_page is True %}

        <div class="text-content">
            
            {% if  blog.content_is_html is True %}
                {{ blog.content|safe }}
            {% else %}
                {{ blog.content|linebreaksbr }}
            {% endif %}
     
        </div>

    {% endif %}

    <div class="blog-meta-container">
        <div class="blog-meta blog-tag">
            <h3 class="blog-meta-title"><i class="fas fa-tag"></i>Tag</h3>
            <div class="blog-meta-text">
                {{ blog.tags }}
            </div>
        </div>
        <div class="blog-meta blog-sector">
            <h3 class="blog-meta-title"><i class="fas fa-industry"></i>Setor</h3>
            <div class="blog-meta-text">
                {{ blog.sector }}
            </div>
        </div>
    </div>

    {% if is_detail_page is not True %}
    <footer class="blog-banco-footer">
        <a href="{% url 'blogs:blog' blog.id %}" class="blog-read-more">
            <i class="fa fa-eye"></i>
            <span>leia mais...</span>
        </a>
    </footer>
    {% endif %}


</div>

blog/templates/blog/partials/search.html
<div class="search-container">
    <div class="container">
        <form action="" class="search-form">
            <input type="search" class="search-input" name="search">
            <button type="submit" class="search-button"><i class="fas fa-search"></i></button>

        </form>
    </div>
</div>

blog/templates/home.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Olá, Mundo!</title>
</head>
<body>
    <h1>Olá, Mundo!</h1>
</body>
</html>

blog/templates/sobre.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>sobre</title>
</head>
<body>
    <h1>Sobre</h1>
</body>
</html>